name = "Peaks"
uuid = "18e31ff7-3703-566c-8e60-38913d67486b"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.4.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3, 4"
julia = "1"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OffsetArrays"]
