name = "Peaks"
uuid = "18e31ff7-3703-566c-8e60-38913d67486b"
authors = ["Allen Hill <allenofthehills@gmail.com>"]
version = "0.5.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Compat = "2.1, 3, 4"
RecipesBase = "1.3"
julia = "1.6"

[extras]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OffsetArrays", "Plots"]
